stages:
  - setup
  - test
  - static-analysis

build-runner-image:
  stage: setup
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/pipeline-runner:main
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --no-cache -t "$IMAGE_NAME" .gitlab/runner-image
    - docker push "$IMAGE_NAME"

phpunit:
  image: docker:latest
  stage: test
  services:
    - docker:dind
  script: bin/ci/test.sh
  parallel:
    matrix:
      - SHOPWARE_VERSION:
          - 'v6.6.0'

rector:
  stage: static-analysis
  image: $CI_REGISTRY_IMAGE/pipeline-runner:main
  script:
    - composer install --no-scripts
    - php vendor/bin/rector --dry-run

phpstan:
  stage: static-analysis
  image: $CI_REGISTRY_IMAGE/pipeline-runner:main
  script:
    - composer install --no-scripts
    - php vendor/bin/phpstan

easy-coding-standard:
  stage: static-analysis
  image: $CI_REGISTRY_IMAGE/pipeline-runner:main
  script:
    - composer install --no-scripts
    - php vendor/bin/ecs

